### ISSUE TITLE
Change celery task function return values

### ISSUE THREAD

**Issue by ricleal** [ornl-ndav/django-remote-submission#10]
The model `Task results` in the admin is not very useful...

The `submit_job_to_server` returns a list of Models (`Result`). Models are not serialisable to JSON by default... It fails...

So, I'm using in django settings:
```
CELERY_ACCEPT_CONTENT = ['pickle'] # also experimented with "json" alone and ['json','pickle']  as well
CELERY_EVENT_SERIALIZER = 'pickle'
CELERY_TASK_SERIALIZER = 'pickle'  
CELERY_RESULT_SERIALIZER = 'pickle'
```
However this renders the `Task results` useless.

Do you have better ideas?

Otherwise I'd suggest in the `submit_job_to_server` to return something else that could be readable... a list of files for example...

**Comment by player1537** [comment]
Oh, whoops, I actually meant to change that from returning a list of models to returning a list of primary keys for the models. Celery prefers it when primary keys are passed around for several reasons, not the least of which is the serializability of them.

I don't know if returning the filenames is particularly useful, just because there's not a clear 1-1 between the remote filenames and the actual data stored locally. However, it's probably also not a great idea to return a list of primary keys because then you have to make multiple queries to retrieve them from the database (e.g. in a `[Results.objects.get(pk) for pk in result_pks]` list comprehension`).

I'm not sure what the best fix for this is. Maybe if we know that it's going to be more common to access everything by filename, we could return a map of `filename => result_pk` that way if you need the filename(s), you have them, and if you need the Result objects (and therefore the local data/path) then you can get them, or if you only need one Result object, you can look it up by filename and then retrieve it from that.

**Comment by ricleal** [comment]
I like the idea of retuning a dict with `Result.pk` and `Result.local_file`. Otherwise just the list of `Result.pk` is OK.

**Comment by player1537** [comment]
I haven't started on this one yet, but I don't envision it being a particularly difficult addition, since it's mostly changing:

```python

    results.sort(key=lambda x: x.remote_filename)

    return results
```

to

```python

    return { r.remote_filename: r.pk for r in results }
```
