### ISSUE TITLE
Web page to show Job list and status

### ISSUE THREAD

**Issue by ricleal** [ornl-ndav/django-remote-submission#11]
Can we create a HTML snipped based on this:
https://github.com/VincentTide/django-channels-celery-example

The idea is to include the snippet in the any desired webpage and list all jobs.

Edit:
This should list all the jobs and respective status, and if clicked should give the Live Log is activated.

**Comment by ricleal** [comment]
Todo after #7 , #9 and #10.

**Comment by player1537** [comment]
For my benefit, this is specifically to have a websocket that will alert you when the job is finished, as well as a different websocket endpoint that you can view the logs live.

**Comment by player1537** [comment]
I think I've got this just about set up. The websocket seems to be working, with the connection staying open and no errors from the Django side. The next thing is to add a button to the example application that starts some sort of default test job, so that I can see if it's actually working.

Then, once that is working, I will need to add a websocket/page to show the live log output. I'm going to have to figure out if it's better to send all of the existing logs for the job on the first connection (probably the better option) or if I should use templates to fill in part of the table in the HTML when I send that to the client.

I'm also going to need to look into getting login working in the example application, since we want to show all a user's jobs and send updates according to the user, unless I can use the admin interface and the superuser account to do it, which is a possibility.

This is currently in the [`add-job-status-channels`](/ornl-ndav/django-remote-submission/tree/add-job-status-channels) branch.

**Comment by player1537** [comment]
Closed by #23.
