### ISSUE TITLE
Implememt delete_key in the Wrapper

### ISSUE THREAD

**Issue by ricleal** [ornl-ndav/django-remote-submission#7]
In the the wrapper, close needs an option to remove the key. Eg.

```python
    def close(self, remove_key=False):
        """Close any open connections and clear their attributes."""
        if remove_key:
           #TODO
           remove_key_if_it_exists(self.client, self.public_key_filename):
```

**Comment by player1537** [comment]
We would need this same flag in `RemoteWrapper.connect` so that this idiom would still work.

```python
with wrapper.connect(password, remove_key=True):
    pass
```

**Comment by ricleal** [comment]
Why?
My drop key code is the following:

```python
wrapper = RemoteWrapper(hostname=server.hostname, username=username)
wrapper.connect(password=password, public_key_filename=public_key_path)
wrapper.close()
```

I though in connect to do just that:
```python
if public_key_filename is not None: 
     self.public_key_filename = public_key_path
```

**Comment by player1537** [comment]
I'm not sure I understand.

We want `close()` to have a flag called `remove_key` that controls whether or not we run the code to remove our key. For the context manager to work so that it will make sure the connection is closed if an exception occurs, it will need to call `close()` for us, which means it will need to take a `remove_key` parameter as well to pass along to `close()`. The place that seems to make the most sense to put that with the context manager is in `connect()` (or in the `__init__()` method) so that `with wrapper.connect():` works.

Is that correct or am I missing something about the idea you had?

**Comment by ricleal** [comment]
Sorry, my fault... it makes sense.... you have to open the connection again to remove the key.
In that case isn't better to have a method called `delete_key` or something that would check for the key  exists and delete it?

My logout code would be:
```python
wrapper = RemoteWrapper(hostname=server.hostname, username=username)
# Either connect here or place the connect inside the delete_key
# wrapper.connect(password=None, public_key_filename=public_key_path)
wrapper.delete_key(public_key_filename=public_key_path)
wrapper.close()
```

**Comment by player1537** [comment]
Yes, unfortunately we will have to connect again in order to delete the key. For that use case, we could add a function like `delete_key` so the order will be:

```python
wrapper = RemoteWrapper(hostname=server.hostname, username=username)
with wrapper.connect(password=None, public_key_filename=public_key_path):
    wrapper.delete_key()
```

(basically yours with a context manager used).

Or we could do

```python
wrapper = RemoteWrapper(hostname=server.hostname, username=username)
wrapper.delete_key(password=None, public_key_filename=public_key_path)
```

I'd be good with either, though I'd probably lean towards the first one, that way if we have other utility functions for doing things on a remote host, they can all have the user of the library call `connect` instead of each function implicitly doing it itself.

**Comment by ricleal** [comment]
My version is just going through your code and finding the minimal amount that would work for me :)
I will get mine as you suggested.

**Comment by player1537** [comment]
I'm about to start working on this one, but I realized that it would actually make more sense to have this as a flag in `submit_job_to_server` task, because deleting the key is agnostic of which of `{Remote,Local}Wrapper` is being used. Although, that also makes it a little harder to just remove the key if you don't want to do anything else, because you would still need to make a new Job that just runs `true` or some other no-op. 

Even if it does get added to the `{Remote,Local}Wrapper`, the main parts of the API of the library are the models and the tasks, not necessarily the wrappers which are meant for internal use.

Another option is to have a utility function that generates the "delete key" Job and not have this built into either the `Wrapper` or tasks. Then the API would be similar to:

```python
job = Job.objects.create(
  server=my_server,
  owner=my_user,
  program=django_remote_submission.remove_key_script,
  interpreter=django_remote_submission.remove_key_interpreter,
)

submit_job_to_server(job.pk)
```

**Comment by ricleal** [comment]
I understand the initial concept but Mathieu and I are using the minimal code (the wrapper) to deploy the key. For us  it doesn't make sense to use the tasks for this... 

For now, and given the time constraints, can you please just add the `delete_key()` to the wrapper?

```python
wrapper = RemoteWrapper(hostname=server.hostname, username=username)
with wrapper.connect(password=None, public_key_filename=public_key_path):
    wrapper.delete_key()
```

We can leave this unfinished for now. If there's time we come back to this.
