### ISSUE TITLE
Result files saved in MEDIA with random name

### ISSUE THREAD

**Issue by ricleal** [ornl-ndav/django-remote-submission#8]
So the files FTPed to local are stored in the `settings.MEDIA_ROOT`.
I guess the problem is that everyone has access to `settings.MEDIA_URL` and guess the file names...

Can we add a random string to the file?
E.g.: `job1/results.txt` would be `job1/RANDOMSTUFF/results.txt`

**Comment by player1537** [comment]
I think adding a random path would be fine. We could change the model so instead of creating a directory with `"job{job.pk}/{orig_filename}"` we could generate a UUID4 when the job is first created or saved and then store directly to `"{uuid}/{orig_filename}"` and skip the `"job{job.pk}"` part entirely.

There's actually a small, related bug with the current setup where it should be stored in something like `media/job1/foo.txt` but is instead stored in `job1/foo.txt`. I think the solution is just to use the `settings.MEDIA_PATH` variable (or whichever one it is exactly) in the `job_results_path` function in `models.py`.

**Comment by ricleal** [comment]
That's OK. Just make it difficult to find the files.

Didn't test it extensively, but if I have defined:
```
MEDIA_URL = '/media/'
MEDIA_ROOT = '../dist/media'
```
works for me...

**Comment by player1537** [comment]
Sounds good, I'll play around when fixing this issue to test out the document describing how to make releases/changes.
